### ISSUE TITLE
Adding Yew

### ISSUE THREAD

**Issue by erlend-sh** [tauri-apps/examples#1]
Our team uses Yew, so it’d be great to have it included for smoke-tests.

https://github.com/yewstack/yew/tree/master/examples/todomvc

**Comment by nothingismagick** [comment]
Its funny, I looked at Yew again today and noticed they are using the exact same todomvc. :D

**Comment by fungos** [comment]
I didn't see this before, but I've added a todomvc yew sample here: https://github.com/tauri-apps/examples/pull/6
With github actions next, I believe this can be considered a smoke test and then this issue can be closed

**Comment by nothingismagick** [comment]
You sir - are correct. And as a matter of fact, you just closed our oldest issue!!! 

#  🎉
