### ISSUE TITLE
tauri/communication misses script

### ISSUE THREAD

**Issue by retorquere** [tauri-apps/examples#442]
The README for `tauri/communication` says to run `yarn tauri dev`, but the `package.json` misses the `script` line for it.

**Comment by nklayman** [comment]
Yarn doesn't need a script in `package.json` to run a npm package binary, it will find it automatically. See [the yarn docs](https://classic.yarnpkg.com/en/docs/cli/run/#toc-yarn-run-script) for more details, specifically:
> [script] can also be any locally installed executable that is inside node_modules/.bin/.

**Comment by retorquere** [comment]
Did not know that, apologies.
