### ISSUE TITLE
How to run the examples?

### ISSUE THREAD

**Issue by retorquere** [tauri-apps/examples#443]
I'm following the toplevel README, and for `mask list examples` I get:

```
react/create-react-app
react/gatsby-themed-site
react/next.js
svelte/svelte-app
vanillajs/monolith
vue/nuxt-app
vue/quasar-app
vue/vue-cli-app
yew/todomvc
communication/dist
communication/src-tauri
flutter_example/lib
flutter_example/src-tauri
flutter_example/test
flutter_example/web
mint-tauri-starter/public
mint-tauri-starter/source
mint-tauri-starter/src-tauri
mint-tauri-starter/tests
reason-react/src
reason-react/src-tauri
```

but `mask run example communication` gives

```
sh: line 0: shopt: globstar: invalid shell option name
unknown project ./communication
```

and `mask run example communication/dist` yields:

```
sh: line 0: shopt: globstar: invalid shell option name
unknown project communication/communication/dist
```

Also, how would I use these samples as a starter for my own project, without cloning it in the root of a [tauri](https://github.com/tauri-apps/tauri) clone?

**Comment by lucasfernog** [comment]
This is now a smoke tests repo rather than an example repo. You'll probably want to just use the `tauri init` command or the `create-tauri-app` NPM package.

The `communication` smoke test was removed, you'll have success running one of the others.
