### ISSUE TITLE
failed to build todomvc

### ISSUE THREAD

**Issue by tlightsky** [tauri-apps/examples#98]
```
error: failed to run custom build command for `yew v0.14.1`

--- stderr
thread 'main' panicked at 'Yew requires selecting either the `web_sys` or `std_web` cargo feature'
```

**Comment by AlveLarsson** [comment]
![image](https://user-images.githubusercontent.com/61861940/78461691-8630b880-76cb-11ea-98f8-0646c8f35fce.png)
std_web have to be added in the cargo.toml in the Yew project folder 
no luck getting web_sys to work for me

can submit a PR to fix this. 

Also, when that is fixed there is this error.
`error: No [package.metadata.bundle] section in Cargo.toml
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart`

**Comment by lucasfernog** [comment]
Can you paste the output of `tauri info`?

**Comment by AlveLarsson** [comment]
Okay 
doing a reinstall of Tauri-bundler fixed it for me.
`cargo install tauri-bundler --force`
so the only issue here is yew's cargo.toml missing feature web_sys
